django_project/blog/urls.py
from django.urls import path
from .views import (
    PostListView, 
    PostDetailView, 
    PostCreateView, 
    PostUpdateView, 
    PostDeleteView,
    UserPostListView,
)
from . import views


app_name = "blog"
urlpatterns = [
    path('', PostListView.as_view(), name='post_list'),
    path('user/<str:username>', UserPostListView.as_view(), name='user_posts'),
    path('post/new/', PostCreateView.as_view(), name='post_create'),
    path('post/<str:pk>/', PostDetailView.as_view(), name='post_detail'),
    path('post/<str:pk>/update/', PostUpdateView.as_view(), name='post_update'),
    path('post/<str:pk>/delete/', PostDeleteView.as_view(), name='post_delete'),
]

django_project/django_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from users import views as user_views

urlpatterns = [
    path('', include('blog.urls')),
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_project/users/urls.py
from django.urls import path
from . import views


app_name = "users"
urlpatterns = [
    path('register', views.register, name='register'),
]

django_project/blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.
class Post(models.Model):
    """ 文章
    title: 标题
    excerpt： 摘要
    cover： 封面
    content： 内容
    author： 作者
    date_posted： 发表时间
    """
    title = models.CharField(max_length=200)
    excerpt = models.CharField(max_length=500, blank=True)
    cover = models.ImageField(upload_to='media/blog/%Y/%m/%d', blank=True)
    content = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    date_posted = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail', kwargs={'pk': self.pk})


    class Meata:
        ordering = ['-date_posted']

django_project/users/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image

# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    nickname = models.CharField(max_length=20, blank=True)
    image = models.ImageField(default='avatar/default.png', upload_to='profile_pics')
    intro = models.CharField(max_length=200, default='这家伙很懒，什么也没留下', blank=True)
    url = models.URLField(blank=True)

    def __str__(self):
        return f'{self.user.username} Profile'

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        img = Image.open(self.image.path)
        if img.width > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)

django_project/users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

    def clean(self):
        user = User.objects.filter(email=self.cleaned_data.get('email'))
        if user:
            raise forms.ValidationError('This email already exists please choose a different one.')
        return super(UserRegisterForm, self).clean()


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['email']

    def clean(self):
        # user = User.objects.filter(email=self.cleaned_data.get('email'))
        # if user:
        #     raise forms.ValidationError('This email already exists please choose a different one.')
        return super(UserUpdateForm, self).clean()


class ProfileUpdateForm(forms.ModelForm):

    class Meta:
        model = Profile
        fields = ['nickname', 'image', 'intro', 'url']

django_project/blog/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import User
from django.views.generic import (
    ListView, 
    DetailView,
    CreateView,
    UpdateView,
    DeleteView
)

from .models import Post


class PostListView(ListView):
    model = Post
    template_name = 'blog/post_list.html'
    context_object_name = 'posts'
    ordering = ['-date_posted']
    # 分页
    paginate_by = 5


class UserPostListView(ListView):
    model = Post
    template_name = 'blog/user_posts.html'
    context_object_name = 'posts'
    # 分页
    paginate_by = 5

    def get_queryset(self):
        user = get_object_or_404(User, username=self.kwargs.get('username'))
        return Post.objects.filter(author=user).order_by('-date_posted')



class PostDetailView(DetailView):
    model = Post
    template_name = 'blog/post_detail.html'
    context_object_name = 'post'


class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    fields = ['title', 'excerpt', 'cover', 'content']
    template_name = 'blog/post_create.html'

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    fields = ['title', 'excerpt', 'cover', 'content']
    template_name = 'blog/post_update.html'
    context_object_name = 'post'

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False


class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    success_url = '/'

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False

django_project/users/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from .forms import UserRegisterForm, UserUpdateForm, ProfileUpdateForm

# Create your views here.


def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            form.save()
            messages.success(
                request, f'Hi, {username}! Your account has been created! You are now able to login.')
            return redirect('login')
    else:
        form = UserRegisterForm()
    return render(request, 'users/register.html', {'form': form, 'title': 'Register'})


@login_required
def profile(request):
    if request.method == "POST":
        user_form = UserUpdateForm(request.POST, instance=request.user)
        profile_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, f'Your account has been updated!')
            return redirect('profile')
    else:
        user_form = UserUpdateForm(instance=request.user)
        profile_form = ProfileUpdateForm(instance=request.user.profile)

    context = {
        "user_form": user_form,
        "profile_form": profile_form,
    }
    return render(request, 'users/profile.html', context)

django_project/templates/base.html
<!doctype html>
<html lang="zn-CN">
<head>
    {% load static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous"> -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    <!-- <title>[DM]Live Each Day As If It Were Your Last.</title> -->
    {% if title %}
        <title>[DM] {{ title }}</title>
    {% else %}
        <title>[DM] Live Each Day As If It Were Your Last.</title>
    {% endif %}
    </head>
<body data-spy="scroll" data-target="#menu">
<header>
    <div id="home">
        <nav class="navbar navbar-expand-md navbar-dark" style="background-color: #A77AC4;">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">
                    <img src="{% static 'img/logo.png' %}" height="48" alt="">
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#menu">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="menu">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item active">
                            <a class="nav-link" href="{% url 'blog:post_list' %}">Blog</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link disabled" href="#">Todo</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Contact</a>
                        </li>
                    </ul>
                    <div class="navbar-nav">
                        {% if user.is_authenticated %}
                        <a class="nav-item nav-link" href="{% url 'profile' %}">Profile</a>
                        <a class="btn btn-outline-light btn-sm my-2 my-sm-0" href="{% url 'logout' %}">Logout</a>
                        {% else %}
                        <a class="btn btn-outline-light btn-sm my-2 my-sm-0" type="button" href="{% url 'login' %}">Login</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </nav>
    </div>
</header>
<main role="main" class="container mt-5">
    <div class="row">
        <div class="col-md-8">
            {% if messages %}
                {% for message in messages  %}
                <div class="alert alert-{{ message.tags }}">
                    {{ message }}
                </div>
                {% endfor %}
            {% endif %}
            {% block main %}{% endblock main %}
        </div>
        <div class="col-md-4">
            <div class="content-section">
                <h3>Sidebar</h3>
                <p class="text-muted">You can put any information here you'd like.</p>
                <ul class="list-group">
                    <li class="list-group-item list-group-item-light">
                        <a class="btn btn-outline-primary" href="{% url 'blog:post_create' %}">New Post</a>
                    </li>
                    <li class="list-group-item list-group-item-light">Latest Posts</li>
                    <li class="list-group-item list-group-item-light">Announcements</li>
                    <li class="list-group-item list-group-item-light">Calendars</li>
                    <li class="list-group-item list-group-item-light">etx</li>
                </ul>
            </div>
        </div>
    </div>
</main>

<footer>
</footer>
<!-- <script src="https://cdn.bootcss.com/jquery/3.4.1/jquery.slim.min.js"></script>
<script src="https://cdn.bootcss.com/twitter-bootstrap/4.3.1/js/bootstrap.bundle.min.js"></script> -->
<script src="{% static 'js/jquery-3.4.1.slim.min.js' %}"></script>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

django_project/templates/blog/post_confirm_delete.html
{% extends 'base.html' %}
{% block main %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-botton mb-4">Delete Post</legend>
                <h2>Are you sure you want to delete the post "{{ object.title }}"</h2>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">Yes, Delete</button>
                <a class="btn btn-outline-secondary" href="{% url 'blog:post_detail' object.id %}">Cancel</a>
            </div>
        </form>
    </div>
{% endblock main %}

django_project/templates/blog/post_create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block main %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-botton mb-4">Blog Post</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Post</button>
            </div>
        </form>
    </div>
{% endblock main %}

django_project/templates/blog/post_detail.html
{% extends 'base.html' %}

{% block main %}
    <article class="media content-section">
        <img class="rounded-circle article-img mr-2" src="{{ post.author.profile.image.url }}" style="width: 3rem; height: 3rem;">
        <div class="media-body">
            <div class="article-metadata">
                <a class="mr-2" href="{% url 'blog:user_posts' post.author.username %}">{{ post.author }}</a>
                <small class="text-muted">{{ post.date_posted }}</small>
                {% if post.author == user %}
                    <div>
                        <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'blog:post_update' post.id %}">Update</a>
                        <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'blog:post_delete' post.id %}">Delete</a>
                    </div>
                {% endif %}
            </div>
            <br>
            <h2 article-title>{{ post.title }}</h2>
            <br>
            {% if post.excerpt %}
            <p class="article-content">{{ post.excerpt|linebreaks }}</p>
            {% endif %}
            <br>
            {{ post.content|linebreaks }}
        </div>
    </article>
{% endblock main %}

django_project/templates/blog/post_list.html
{% extends 'base.html' %}

{% block main %}
    {% for post in posts %}
        <article class="media content-section">
            <img class="rounded-circle article-img mr-2" src="{{ post.author.profile.image.url }}" style="width: 3rem; height: 3rem;">
            <div class="media-body">
                <div class="article-metadata">
                    <a class="mr-2" href="{% url 'blog:user_posts' post.author.username %}">{{ post.author }}</a>
                    <small class="text-muted">{{ post.date_posted|date:"F d, Y" }}</small>
                </div>
                <h2><a class="article-title" href="{% url 'blog:post_detail' post.pk %}">{{ post.title }}</a></h2>
                {% if post.excerpt %}
                <p class="article-content">{{ post.excerpt|linebreaks }}</p>
                {% else %}
                <p class="article-content">{{ post.content|linebreaks|slice:'100' }}</p>
                {% endif %}
            </div>
        </article>
    {% endfor %}
    <!-- paginate -->
    {% if is_paginated %}
    <div class="container text-center mt-3">
        {% if page_obj.has_previous %}
            <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
        {% endif %}
        {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
                <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
            {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
            {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
        {% endif %}
    </div>
    {% endif %}
{% endblock main %}

django_project/templates/blog/post_update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block main %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-botton mb-4">Blog Post</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Update</button>
            </div>
        </form>
    </div>
{% endblock main %}

django_project/templates/blog/user_posts.html
{% extends 'base.html' %}

{% block main %}
    <h1 class="mb-3">Post by {{ view.kwargs.username }} ({{ page_obj.paginator.count }})</h1>
    {% for post in posts %}
        <article class="media content-section">
            <img class="rounded-circle article-img mr-2" src="{{ post.author.profile.image.url }}" style="width: 3rem; height: 3rem;">
            <div class="media-body">
                <div class="article-metadata">
                    <a class="mr-2" href="{% url 'blog:user_posts' post.author.username %}">{{ post.author }}</a>
                    <small class="text-muted">{{ post.date_posted|date:"F d, Y" }}</small>
                </div>
                <h2><a class="article-title" href="{% url 'blog:post_detail' post.pk %}">{{ post.title }}</a></h2>
                {% if post.excerpt %}
                <p class="article-content">{{ post.excerpt|linebreaks }}</p>
                {% else %}
                <p class="article-content">{{ post.content|linebreaks|slice:'100' }}</p>
                {% endif %}
            </div>
        </article>
    {% endfor %}
    <!-- paginate -->
    {% if is_paginated %}
    <div class="container text-center mt-3">
        {% if page_obj.has_previous %}
            <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
        {% endif %}
        {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
                <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
            {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
            {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
        {% endif %}
    </div>
    {% endif %}
{% endblock main %}

django_project/templates/users/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block main %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-botton mb-4">Login</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Login</button>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Nedd An Account? <a class="ml-2" href="{% url 'register' %}">Sign Up Now</a>
            </small>
        </div>
    </div>
{% endblock main %}

django_project/templates/users/logout.html
{% extends 'base.html' %}
{% block main %}
    <h2>You have been logged out.</h2>
    <div class="border-top pt-3">
        <small class="text-muted">
            <a href="{% url 'login' %}">Login Again</a>
        </small>
    </div>
{% endblock main %}

django_project/templates/users/profile.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block main %}
    <div class="row">
        <div class="col-md-8 mb-3">
            <img class="rounded-circle account-img mr-2" src="{{ user.profile.image.url }}" style="width: 5rem; height: 5rem;">
            <div class="media-body">
                <h2 class="account-heading">{{ user }}</h2>
                <p class="text-secondary">{{ user.email }}</p>
            </div>
        </div>
        <div class="col-md-8">
            <form action="#" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4">User Profile</legend>
                    {{ user_form|crispy }}
                    {{ profile_form|crispy }}
                </fieldset>
                <div class="form-group">
                    <button class="btn btn-outline-info" type="submit">Update</button>
                </div>
            </form>
        </div>
    </div>
{% endblock main %}

django_project/templates/users/register.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block main %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-botton mb-4">Welecom Join!</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Sign Up</button>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Already Have An Account? <a class="ml-2" href="{% url 'login' %}">Sign In</a>
            </small>
        </div>
    </div>
{% endblock main %}